"""Regenerate docs/RESULTS.md from scratch.

Every number published in the README comes from this script, so a reader
can reproduce the scoreboard with one command.

    .venv/bin/python -m scripts.run_backtest
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from src.evaluation.backtest import run_backtest
from src.features.build_features import build_features_daily_iqa
from src.models.classifier import COST_RATIO
from src.models.training_daily import GOLD_PATH

CONTIGUOUS_END = "2026-01-18"
DEFAULT_OUT = Path("docs/RESULTS.md")


def render_markdown(
    results: pd.DataFrame, cost_ratio: float, extra_sections: str | None
) -> str:
    """Render the scoreboard as Markdown."""
    lines = [
        "# Results",
        "",
        "Generated by `python -m scripts.run_backtest`. Do not edit by hand.",
        "",
        "MASE is scaled to persistence: **1.00 ties it, below 1.00 beats it**.",
        "",
        "## Regression - mean MASE across folds",
        "",
    ]
    pivot = results.groupby(["candidate", "horizon"])["mase"].mean().unstack("horizon")
    pivot = pivot.sort_values(pivot.columns[0])
    header = " | ".join(f"h{int(c) * 24}" for c in pivot.columns)
    lines += [f"| model | {header} |", "|---|" + "---|" * len(pivot.columns)]
    for name, row in pivot.iterrows():
        cells = " | ".join(f"{v:.3f}" for v in row)
        lines.append(f"| `{name}` | {cells} |")

    first_horizon = results["horizon"].min()
    wins = results[results["horizon"] == first_horizon]
    lines += ["", f"## Folds won against persistence (h{int(first_horizon) * 24})", ""]
    lines += ["| model | folds beaten | of |", "|---|---|---|"]
    for name, group in wins.groupby("candidate"):
        lines.append(f"| `{name}` | {int((group['mase'] < 1).sum())} | {len(group)} |")

    best_name = pivot.index[0]
    best_value = float(pivot.iloc[0, 0])
    lines += ["", "## Verdict", ""]
    if best_value < 1.0:
        lines.append(
            f"`{best_name}` beats persistence, mean MASE **{best_value:.3f}** "
            f"({(1 - best_value) * 100:.0f}% better than doing nothing)."
        )
    else:
        lines.append(
            "**No model beat persistence.** The trivial 'tomorrow = today' "
            "baseline remains the best available forecast."
        )

    if extra_sections:
        lines += ["", extra_sections]

    lines += [
        "",
        "---",
        "",
        f"Data through {CONTIGUOUS_END}. Alert cost ratio {cost_ratio:.0f}:1.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser("regenerate the results scoreboard")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--folds", type=int, default=5)
    parser.add_argument("--test-days", type=int, default=90)
    args = parser.parse_args()

    gold = pd.read_parquet(GOLD_PATH)
    frame, features = build_features_daily_iqa(gold)

    results = run_backtest(
        frame,
        features,
        n_folds=args.folds,
        test_days=args.test_days,
        horizons=(1, 2, 3),
        max_date=CONTIGUOUS_END,
    )

    summary = results.groupby("candidate")["mase"].mean().sort_values()
    print(summary.round(3).to_string())
    print(f"\nbest: {summary.index[0]} (mean MASE {summary.iloc[0]:.3f})")
    if summary.iloc[0] >= 1.0:
        print("NOTE: nothing beat persistence. Say so plainly in the README.")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_markdown(results, COST_RATIO, None))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
